### ISSUE TITLE
License clarification

### ISSUE THREAD

**Issue by LukasWohlfart1** [yairEO/position#7]
Hello @yairEO 

there is contradicting information on licensing within your project: 

- LICENSE file indicates AGPL https://github.com/yairEO/position/blob/master/LICENSE
- package.json indicates MIT https://github.com/yairEO/position/blob/master/package.json#L14

Would you be so kind to confirm wich of the licenses applies and maybe adjust accordingly in the repository to avoid confusion?

Best Regards

**Comment by LukasWohlfart1** [comment]
Hi @yairEO any thoughts on this?

**Comment by yairEO** [comment]
Here, I've hanged the license to MIT (for now only on github) until I release a new NPM version with the updated license.
